services:
  db:
    image: postgres:17-alpine3.21
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-18T16-25-55Z
    restart: on-failure
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: beetroot
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
    command: minio server /data
  valkey:
    image: valkey/valkey:8.0-alpine3.21
    restart: on-failure
    volumes:
      - valkey-data:/data
    ports:
      - 6379:6379
volumes:
  db-data:
  minio-data:
  valkey-data:
