// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: seat-lock.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetLockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    *string `protobuf:"bytes,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SeatIndex *string `protobuf:"bytes,2,req,name=seat_index,json=seatIndex" json:"seat_index,omitempty"`
}

func (x *SetLockRequest) Reset() {
	*x = SetLockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seat_lock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLockRequest) ProtoMessage() {}

func (x *SetLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_lock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLockRequest.ProtoReflect.Descriptor instead.
func (*SetLockRequest) Descriptor() ([]byte, []int) {
	return file_seat_lock_proto_rawDescGZIP(), []int{0}
}

func (x *SetLockRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *SetLockRequest) GetSeatIndex() string {
	if x != nil && x.SeatIndex != nil {
		return *x.SeatIndex
	}
	return ""
}

type GetLockByUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId *string `protobuf:"bytes,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (x *GetLockByUserIdRequest) Reset() {
	*x = GetLockByUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seat_lock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLockByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockByUserIdRequest) ProtoMessage() {}

func (x *GetLockByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_lock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetLockByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_seat_lock_proto_rawDescGZIP(), []int{1}
}

func (x *GetLockByUserIdRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type GetLockBySeatIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatIndex *string `protobuf:"bytes,1,req,name=seat_index,json=seatIndex" json:"seat_index,omitempty"`
}

func (x *GetLockBySeatIndexRequest) Reset() {
	*x = GetLockBySeatIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seat_lock_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLockBySeatIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockBySeatIndexRequest) ProtoMessage() {}

func (x *GetLockBySeatIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_lock_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockBySeatIndexRequest.ProtoReflect.Descriptor instead.
func (*GetLockBySeatIndexRequest) Descriptor() ([]byte, []int) {
	return file_seat_lock_proto_rawDescGZIP(), []int{2}
}

func (x *GetLockBySeatIndexRequest) GetSeatIndex() string {
	if x != nil && x.SeatIndex != nil {
		return *x.SeatIndex
	}
	return ""
}

type LockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *bool `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seat_lock_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_lock_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_seat_lock_proto_rawDescGZIP(), []int{3}
}

func (x *LockResponse) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

var File_seat_lock_proto protoreflect.FileDescriptor

var file_seat_lock_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x65, 0x61, 0x74, 0x2d, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x73, 0x65, 0x61, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x4c,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x31, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x6b,
	0x42, 0x79, 0x53, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x22, 0x26, 0x0a, 0x0c, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xe7, 0x01, 0x0a, 0x08, 0x53, 0x65,
	0x61, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x3b, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63,
	0x6b, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x65, 0x74,
	0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x4b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x20, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x4c, 0x6f, 0x63,
	0x6b, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x4c,
	0x6f, 0x63, 0x6b, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x51, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x53, 0x65, 0x61,
	0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x23, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x4c, 0x6f, 0x63,
	0x6b, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x53, 0x65, 0x61, 0x74, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x65,
	0x61, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x03, 0x5a, 0x01, 0x2f,
}

var (
	file_seat_lock_proto_rawDescOnce sync.Once
	file_seat_lock_proto_rawDescData = file_seat_lock_proto_rawDesc
)

func file_seat_lock_proto_rawDescGZIP() []byte {
	file_seat_lock_proto_rawDescOnce.Do(func() {
		file_seat_lock_proto_rawDescData = protoimpl.X.CompressGZIP(file_seat_lock_proto_rawDescData)
	})
	return file_seat_lock_proto_rawDescData
}

var file_seat_lock_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_seat_lock_proto_goTypes = []interface{}{
	(*SetLockRequest)(nil),            // 0: seatLock.SetLockRequest
	(*GetLockByUserIdRequest)(nil),    // 1: seatLock.GetLockByUserIdRequest
	(*GetLockBySeatIndexRequest)(nil), // 2: seatLock.GetLockBySeatIndexRequest
	(*LockResponse)(nil),              // 3: seatLock.LockResponse
	(*emptypb.Empty)(nil),             // 4: google.protobuf.Empty
}
var file_seat_lock_proto_depIdxs = []int32{
	0, // 0: seatLock.SeatLock.SetLock:input_type -> seatLock.SetLockRequest
	1, // 1: seatLock.SeatLock.GetLockByUserID:input_type -> seatLock.GetLockByUserIdRequest
	2, // 2: seatLock.SeatLock.GetLockBySeatIndex:input_type -> seatLock.GetLockBySeatIndexRequest
	4, // 3: seatLock.SeatLock.SetLock:output_type -> google.protobuf.Empty
	3, // 4: seatLock.SeatLock.GetLockByUserID:output_type -> seatLock.LockResponse
	3, // 5: seatLock.SeatLock.GetLockBySeatIndex:output_type -> seatLock.LockResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seat_lock_proto_init() }
func file_seat_lock_proto_init() {
	if File_seat_lock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seat_lock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seat_lock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLockByUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seat_lock_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLockBySeatIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seat_lock_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seat_lock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seat_lock_proto_goTypes,
		DependencyIndexes: file_seat_lock_proto_depIdxs,
		MessageInfos:      file_seat_lock_proto_msgTypes,
	}.Build()
	File_seat_lock_proto = out.File
	file_seat_lock_proto_rawDesc = nil
	file_seat_lock_proto_goTypes = nil
	file_seat_lock_proto_depIdxs = nil
}
