apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: backend
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      name: client
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: gitlab.prodcontest.ru:5050/team-8/backend/client:master
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: client-cm
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: client-lb
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: client-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-cm
  namespace: backend
data:
  SERVICE_ADDRESS: "0.0.0.0:8080"
  DATABASE_URL: "postgres://yugabyteuser:ivvS3w449NOj@yb-tservers.yugabyte.svc.cluster.local:5433/client?sslmode=disable"
  JWT_SECRET: "Aksdjirfmalsdmrvjnamsd"
  RESERVATION_SERVICE_ADDRESS: "reservation-lb.backend.svc.cluster.local:80"
