apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-deployment
  namespace: backend
  labels:
    app: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coworking
  template:
    metadata:
      name: coworking
      labels:
        app: coworking
    spec:
      containers:
        - name: coworking
          image: gitlab.prodcontest.ru:5050/team-8/backend/coworking:master
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: coworking-cm
          ports:
            - containerPort: 8080
              protocol: TCP
      initContainers:
        - name: goose
          image: gitlab.prodcontest.ru:5050/team-8/backend/goose:master
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: coworking-goose-cm
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: coworking-lb
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: coworking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coworking-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coworking-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-cm
  namespace: backend
data:
  SERVER_PORT: "8080"
  DB_HOST: "yb-tservers.yugabyte.svc.cluster.local"
  DB_PORT: "5433"
  DB_USER: "yugabyteuser"
  DB_PASS: "ivvS3w449NOj"
  DB_DATABASE: "coworking"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-goose-cm
  namespace: backend
data:
  GOOSE_DRIVER: "postgres"
  GOOSE_DBSTRING: "postgres://yugabyteuser:ivvS3w449NOj@yb-tservers.yugabyte.svc.cluster.local:5433/coworking?sslmode=disable"
  GOOSE_MIGRATION_DIR: "./migrations"