apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: backend
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gitlab.prodcontest.ru:5050/team-8/backend/gateway:master
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: gateway-cm
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-lb
  namespace: backend
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-cm
  namespace: backend
data:
  RUST_LOG: "debug"
  SERVER_ADDRESS: "0.0.0.0:8080"
  COWORKING_ID: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  ADMIN_SERVICE_ADDRESS: "admin-lb.backend.svc.cluster.local:80"
  CLIENT_SERVICE_ADDRESS: "client-lb.backend.svc.cluster.local:80"
  COWORKING_SERVICE_ADDRESS: "coworking-lb.backend.svc.cluster.local:80"
  RESERVATION_SERVICE_ADDRESS: "reservation-lb.backend.svc.cluster.local:80"
  MAIL_SERVICE_ADDRESS: "mail-lb.backend.svc.cluster.local:80"
  NOTIFICATION_SERVICE_ADDRESS: "notification-lb.backend.svc.cluster.local:80"
