apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deployment
  namespace: backend
  labels:
    app: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      name: image
      labels:
        app: image
    spec:
      containers:
        - name: image
          image: gitlab.prodcontest.ru:5050/team-8/backend/image:master
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: image-cm
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: image-lb
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: image
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: image-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: image-cm
  namespace: backend
data:
  SERVER_PORT: "8080"

  MINIO_HOST: "minio.minio-tenant.svc.cluster.local:443"
  MINIO_LOGIN: "minio"
  MINIO_PASSWORD: "RRvvJaHsC"

  COWORKING_BUCKET: "coworking-images"
  SEAT_BUCKET: "seat-images"
  FEATURES_BUCKET: "feature-images"
  AVATAR_BUCKET: "avatar-images"
