apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-deployment
  namespace: backend
  labels:
    app: mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail
  template:
    metadata:
      name: mail
      labels:
        app: mail
    spec:
      containers:
        - name: mail
          image: gitlab.prodcontest.ru:5050/team-8/backend/mail:master
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mail-cm
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mail-lb
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: mail
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mail-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mail-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-cm
  namespace: backend
data:
  SERVER_PORT: "8080"
  MAIL_PASSWORD: ""
  MAIL_PORT: "587"
  MAIL_HOST: ""
  MAIL_EMAIL: ""
