apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: backend
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: gitlab.prodcontest.ru:5050/team-8/backend/notification:master
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: notification-cm
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notification-lb
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-cm
  namespace: backend
data:
  SERVICE_ADDRESS: "0.0.0.0:8080"
  COWORKING_ID: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  CLIENT_SERVICE_ADDRESS: "client-lb.backend.svc.cluster.local:80"
  COWORKING_SERVICE_ADDRESS: "coworking-lb.backend.svc.cluster.local:80"
  RESERVATION_SERVICE_ADDRESS: "reservation-lb.backend.svc.cluster.local:80"
  MAIL_SERVICE_ADDRESS: "mail-lb.backend.svc.cluster.local:80"
