apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-deployment
  namespace: backend
  labels:
    app: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      name: reservation
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: gitlab.prodcontest.ru:5050/team-8/backend/reservation:master
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: reservation-cm
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-lb
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: reservation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reservation-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reservation-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reservation-cm
  namespace: backend
data:
  PORT: "8080"
  POSTGRES_DATABASE: "reservation"
  POSTGRES_HOST: "yb-tservers.yugabyte.svc.cluster.local"
  POSTGRES_PASSWORD: "ivvS3w449NOj"
  POSTGRES_PORT: "5433"
  POSTGRES_USERNAME: "yugabyteuser"

